CREATE TABLE IF NOT EXISTS `bs_taxi_fleet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(60) NOT NULL,
  `plate` VARCHAR(12) NOT NULL,
  `fuel` FLOAT NOT NULL DEFAULT 100,
  `engine_health` FLOAT NOT NULL DEFAULT 1000,
  `body_health` FLOAT NOT NULL DEFAULT 1000,
  `stored` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_plate` (`plate`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
